"use strict";
const app=document.querySelector("#app"),root=document.documentElement;
const games=[
["reflex","⚡","Reflejo relámpago",5.5,"Pulsa el círculo cuando se ponga verde.","Espera y pulsa solo cuando esté verde.","Si pulsas antes."],
["duck","🦆","Atrapa al pato",8,"Atrapa al pato 12 veces.","Tócalo cada vez que cambie de sitio.","Si tocas fuera o no llegas a 12."],
["math","➕","Cuenta flash",11,"Resuelve la operación.","Escribe el resultado.","Si fallas."],
["multiply","✖️","Multiplicación exprés",12,"Resuelve la multiplicación.","Calcula y escribe.","Si fallas."],
["intruder","🍎","El intruso",7,"Encuentra el diferente entre 49.","Toca el único distinto.","Si tocas uno normal."],
["memory","🧠","Memoria 6",10,"Recuerda 6 números.","Mira y después escríbelos seguidos.","Si fallas la secuencia."],
["pulse","🎯","Pulso perfecto",6.5,"Detén el punto en verde.","Pulsa PARAR en la zona verde.","Si paras fuera."],
["order","🔢","Orden exacto",7,"Pulsa del 1 al 8.","Encuentra cada número en orden.","Si te equivocas."],
["code","🔐","Código fugaz",8,"Memoriza 5 cifras.","Míralas y repítelas.","Si fallas."],
["taps","👆","Doble exacto",6.5,"Consigue exactamente 18 toques.","Toca hasta llegar a 18.","Si acaba el tiempo."],
["colorWords","🎨","Color tramposo",7,"Elige el texto correcto.","Lee la palabra, ignora su color.","Si eliges otra."],
["targetSum","🎯","Suma objetivo",9,"Encuentra dos números que sumen el objetivo.","Toca la pareja correcta.","Si no suma."],
["arrow","🧭","Flecha tramposa",6.5,"Sigue la dirección de la flecha.","Elige su dirección.","Si fallas."],
["sequence","🧩","Memoria musical",8.5,"Repite 6 posiciones.","Memoriza los destellos y repítelos.","Si fallas."],
["ghost","👻","Número fantasma",7,"Encuentra el número que falta entre 15.","Toca el ausente.","Si tocas uno que aparece."],
["precision","🎯","Toque preciso",5.5,"Toca el objetivo móvil.","Sigue y tócalo.","Si tocas fuera."],
["pairs","🐶","Rebelde emoji",8,"Encuentra el diferente entre 25.","Busca al único distinto.","Si tocas uno normal."],
["compare","📈","Mayor o menor",6,"Decide cuál es mayor.","Pulsa MAYOR o MENOR.","Si respondes mal."],
["changeColor","🔴","Cambio de color",6.5,"Pulsa el color pedido tras el cambio.","Espera AHORA y toca el color.","Si fallas."],
["mirror","🔄","Palabra espejo",8,"Descifra la palabra invertida.","Escribe la palabra normal.","Si fallas."]
].map(x=>({id:x[0],emoji:x[1],name:x[2],time:x[3],goal:x[4],how:x[5],lose:x[6]}));
const state={token:0,active:false,ended:false,streak:0,timers:new Set(),frames:new Set(),controller:null,audio:null};
const pick=a=>a[Math.floor(Math.random()*a.length)],num=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=num(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
const btn=(t,id="")=>`<button class="btn primary" ${id?`id="${id}"`:""}>${t}</button>`;
function clear(){state.timers.forEach(clearTimeout);state.timers.clear();state.frames.forEach(cancelAnimationFrame);state.frames.clear();if(state.controller)state.controller.abort();state.controller=null;state.active=false}
function delay(fn,ms,token=state.token){let t=setTimeout(()=>{state.timers.delete(t);if(token===state.token&&!state.ended)fn()},ms);state.timers.add(t);return t}
function frame(fn){let id=requestAnimationFrame(t=>{state.frames.delete(id);if(!state.ended)fn(t)});state.frames.add(id)}
function bind(el,e,fn){el.addEventListener(e,fn,{signal:state.controller.signal})}
function sound(type){let A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!state.audio)state.audio=new A;let c=state.audio;if(c.state==="suspended")c.resume();let d={click:[360,.06,"sine"],tick:[620,.08,"square"],start:[880,.14,"sine"],good:[750,.18,"triangle"],bad:[150,.22,"sawtooth"],urgent:[980,.08,"square"],win:[680,.35,"triangle"],lose:[130,.3,"sawtooth"]}[type]||[360,.06,"sine"],o=c.createOscillator(),g=c.createGain(),n=c.currentTime;o.type=d[2];o.frequency.setValueAtTime(d[0],n);if(type==="win")o.frequency.exponentialRampToValueAtTime(1150,n+d[1]);if(type==="lose")o.frequency.exponentialRampToValueAtTime(70,n+d[1]);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.24,n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+d[1]);o.connect(g).connect(c.destination);o.start(n);o.stop(n+d[1]+.03)}
function home(){clear();state.token++;state.ended=false;state.streak=0;app.innerHTML=`<section class="screen home-screen enter"><div class="floating-die">🧩</div><p class="eyebrow">MINIJUEGO DEL JUEGO DE MESA</p><h1>CONSIGUE<br><span>LA PIEZA</span></h1><p class="home-copy">Supera 3 retos seguidos<br>para ganar tu pieza.</p>${btn("EMPEZAR 🚀","play")}<p class="small-note">20 retos · 5% cada uno · MODO DIFÍCIL</p></section>`;document.querySelector("#play").onclick=()=>{sound("click");choose()}}
function choose(){instructions(games[num(0,games.length-1)])}
function instructions(g){clear();state.token++;root.style.setProperty("--accent", "#ffce4a");let r=3-state.streak;app.innerHTML=`<section class="screen instructions enter"><div class="game-icon">${g.emoji}</div><p class="eyebrow">RETO ALEATORIO · DIFÍCIL</p><p class="remaining-callout">FALTAN <b>${r}</b> ${r===1?"RETO":"RETOS"} PARA LA PIEZA</p><h2>${g.name}</h2><div class="instruction-card"><div><span>🎯 OBJETIVO</span><p>${g.goal}</p></div><div><span>👆 CÓMO SE JUEGA</span><p>${g.how}</p></div><div><span>💥 PIERDES SI…</span><p>${g.lose}</p></div><div class="instruction-time"><span>⏱️ TIEMPO</span><strong>${g.time} segundos</strong></div></div><p class="one-chance">⚠️ Solo tienes una oportunidad</p>${btn("ESTOY LISTO 🚀","ready")}</section>`;document.querySelector("#ready").onclick=()=>{sound("click");countdown(g)}}
function countdown(g){clear();let token=++state.token;app.innerHTML=`<section class="screen countdown-screen"><div id="count" class="countdown-number"></div><p>Prepárate…</p></section>`;let v=["3","2","1","¡YA!"];let i=0;function n(){if(i===v.length)return start(g);let e=document.querySelector("#count");e.textContent=v[i];e.classList.remove("pop");void e.offsetWidth;e.classList.add("pop");sound(i===3?"start":"tick");i++;delay(n,600,token)}n()}
function start(g){clear();let token=++state.token;state.active=true;state.ended=false;state.controller=new AbortController();let r=3-state.streak;app.innerHTML=`<section class="play-screen enter"><header class="play-header"><div class="challenge-label"><span>${g.emoji}</span><strong>${g.name}</strong><span class="streak">FALTAN ${r}</span></div><div class="timer-row"><span id="clock">⏱️ ${g.time.toFixed(1)} s</span><span class="chance">1 OPORTUNIDAD</span></div><div class="time-track"><i id="bar"></i></div></header><section class="game-area" id="area"></section></section>`;timer(g.time,token);mount(g.id,document.querySelector("#area"))}
function timer(total,token){let s=performance.now(),beep=false;function t(now){if(token!==state.token||state.ended)return;let rem=Math.max(0,total-(now-s)/1000),q=rem/total,c=document.querySelector("#clock"),b=document.querySelector("#bar");c.textContent=`⏱️ ${rem.toFixed(1)} s`;c.classList.toggle("urgent",q<.25);b.style.width=`${q*100}%`;b.dataset.level=q>.5?"safe":q>.25?"warning":"danger";if(q<.25&&!beep){beep=true;sound("urgent")}if(!rem)return result(false,"Se acabó el tiempo.");frame(t)}frame(t)}
function result(win,text){if(state.ended||!state.active)return;state.ended=true;clear();sound(win?"win":"lose");if(win)state.streak++;let won=win&&state.streak===3,r=3-state.streak;app.innerHTML=`<section class="screen result-screen ${win?"win":"loss"} enter"><div class="result-burst">${won?"🧩":win?"🎉":"💥"}</div><p class="eyebrow">${won?"¡RACHA COMPLETA!":win?`TE FALTAN ${r} ${r===1?"RETO":"RETOS"}`:"LA RACHA VUELVE A CERO"}</p><h2>${won?"¡CONSEGUISTE LA PIEZA!":win?"¡RETO SUPERADO!":"A LA PRÓXIMA"}</h2><p class="result-copy">${won?"Has superado 3 retos seguidos. Esta pieza es tuya.":text||"¡Muy buena jugada!"}</p>${btn(won?"SIGUIENTE ➡️":win?"CONTINUAR ➡️":"EMPEZAR DE NUEVO 🚀","again")}</section>`;document.querySelector("#again").onclick=()=>{sound("click");if(won)return home();if(!win)state.streak=0;choose()}}
function form(area,q,ans){area.innerHTML=`<div class="question-card"><p class="game-kicker">CALCULA Y DECIDE</p><div class="math-question">${q}</div><form><input id="answer" inputmode="numeric" autocomplete="off" placeholder="Tu respuesta" required>${btn("COMPROBAR")}</form></div>`;bind(area,"submit",e=>{e.preventDefault();result(Number(document.querySelector("#answer").value)===ans,"¡Respuesta correcta!")})}
function pos(f,z=48){return{left:num(8,Math.max(8,f.clientWidth-z-8))+"px",top:num(58,Math.max(58,f.clientHeight-z-8))+"px"}}
function mount(id,a){
if(id==="reflex"){a.innerHTML=`<div class="reflex-wrap"><p>ESPERA AL VERDE</p><button id="dot" class="reflex-dot waiting"></button></div>`;let go=false;delay(()=>{go=true;document.querySelector("#dot").className="reflex-dot go"},num(900,3000));bind(a,"click",e=>{if(e.target.id!=="dot")return result(false,"¡Demasiado pronto!");if(!go)return result(false,"Todavía estaba rojo.");sound("good");result(true,"¡Reflejos de rayo!")});return}
if(id==="duck"){let n=0;a.innerHTML=`<div class="catch-field" id="field"><p class="catch-count">PATOS: <b id="score">0</b> / 12</p><button id="duck" class="moving-duck" style="width:48px;height:48px;font-size:24px;padding:0">🦆</button></div>`;let f=document.querySelector("#field"),d=document.querySelector("#duck"),move=()=>Object.assign(d.style,pos(f));move();bind(a,"click",e=>{if(e.target!==d)result(false,"¡Fallaste al pato!")});bind(d,"click",e=>{e.stopPropagation();sound("click");if(++n===12)result(true,"¡Doce patos atrapados!");else{document.querySelector("#score").textContent=n;move()}});return}
if(id==="math"){let x=num(20,70),y=num(10,45),op=pick(["+","-"]);if(op==="-"&&y>x)[x,y]=[y,x];form(a,`${x} ${op} ${y}`,op==="+"?x+y:x-y);return}
if(id==="multiply"){let x=num(7,14),y=num(6,12);form(a,`${x} × ${y}`,x*y);return}
if(id==="intruder"){let pairs=[["🍎","🍐"],["🌻","🌼"],["🐸","🦎"],["🍪","🥨"],["⚽","🏀"],["🐱","🐯"],["🍋","🍊"],["⭐","🌟"]],p=pick(pairs),sp=num(0,48);a.innerHTML=`<p class="game-kicker">TOCA EL DISTINTO</p><div class="emoji-grid hard-grid" style="grid-template-columns:repeat(7,minmax(0,1fr));gap:4px">${Array.from({length:49},(_,i)=>`<button class="emoji-tile" data-ok="${i===sp}" style="font-size:20px;min-height:36px;padding:1px">${i===sp?p[1]:p[0]}</button>`).join("")}</div>`;bind(a,"click",e=>{let t=e.target.closest(".emoji-tile");if(t)result(t.dataset.ok==="true",t.dataset.ok==="true"?"¡Ojo de águila!":"Ese no era.")});return}
if(id==="memory"){let s=Array.from({length:6},()=>num(0,9)).join("");a.innerHTML=`<div class="memory-card"><p class="game-kicker">MEMORÍZALO</p><div class="memory-code">${s}</div><p>Desaparece en un instante…</p></div>`;delay(()=>{a.innerHTML=`<div class="question-card"><p class="game-kicker">AHORA TÚ</p><form><input id="answer" inputmode="numeric" placeholder="6 cifras" autocomplete="off">${btn("COMPROBAR")}</form></div>`;bind(a,"submit",e=>{e.preventDefault();result(document.querySelector("#answer").value===s,"Secuencia correcta.")})},1800);return}
if(id==="pulse"){a.innerHTML=`<div class="pulse-card"><p>DETÉN EL PUNTO EN VERDE</p><div class="pulse-track"><i class="pulse-zone" style="left:42%;width:16%"></i><i class="pulse-marker" id="marker"></i></div>${btn("PARAR","stop")}</div>`;let m=document.querySelector("#marker"),start=performance.now();function go(t){let x=(Math.sin((t-start)/260)+1)/2*100;m.style.left=x+"%";if(!state.ended)frame(go)}frame(go);bind(document.querySelector("#stop"),"click",()=>{let x=parseFloat(m.style.left);result(x>=42&&x<=58,x>=42&&x<=58?"¡Pulso perfecto!":"¡Demasiado lejos!")});return}
if(id==="order"){let nums=shuffle([1,2,3,4,5,6,7,8]),next=1;a.innerHTML=`<div class="number-grid">${nums.map(n=>`<button class="number-tile" data-n="${n}">${n}</button>`).join("")}</div>`;bind(a,"click",e=>{let t=e.target.closest(".number-tile");if(!t)return;let n=+t.dataset.n;if(n!==next)return result(false,"¡Orden incorrecto!");t.disabled=true;if(++next===9)result(true,"¡Ocho en orden perfecto!")});return}
if(id==="code"){let s=String(num(10000,99999));a.innerHTML=`<div class="memory-card"><p class="game-kicker">CÓDIGO</p><div class="memory-code">${s}</div><p>Desaparece pronto…</p></div>`;delay(()=>{a.innerHTML=`<div class="question-card"><form><input id="answer" inputmode="numeric" placeholder="Código" autocomplete="off">${btn("COMPROBAR")}</form></div>`;bind(a,"submit",e=>{e.preventDefault();result(document.querySelector("#answer").value===s,"¡Código descifrado!")})},1400);return}
if(id==="taps"){let n=0;a.innerHTML=`<div class="taps-card"><p>TOQUES: <b id="n">0</b> / 18</p><button id="tap" class="tap-button">¡TOCA!</button><small>Exactamente 18.</small></div>`;bind(document.querySelector("#tap"),"click",()=>{n++;document.querySelector("#n").textContent=n;if(n>18)result(false,"¡Te pasaste!");if(n===18)result(true,"¡18 exactos!")});return}
if(id==="colorWords"){let colors=["ROJO","AZUL","VERDE","AMARILLO"],target=pick(colors);a.innerHTML=`<div class="word-target">TOCA: ${target}</div><div class="color-word-grid">${shuffle(colors).map((x,i)=>`<button class="color-word" data-x="${x}" style="background:${["#e74c5c","#3b82d0","#36b37e","#e4b83d"][colors.indexOf(pick(colors))]}">${x}</button>`).join("")}</div>`;bind(a,"click",e=>{let t=e.target.closest(".color-word");if(t)result(t.dataset.x===target,"¡Buenísima lectura!")});return}
if(id==="targetSum"){let x=num(5,30),y=num(5,30),target=x+y,arr=shuffle([x,y,num(2,20),num(2,20),num(2,20),num(2,20)]);a.innerHTML=`<div class="sum-game"><div class="sum-target">${target}</div><p>ELIGE DOS</p><div class="sum-options">${arr.map((n,i)=>`<button class="sum-option" data-i="${i}" data-n="${n}">${n}</button>`).join("")}</div></div>`;let chosen=[];bind(a,"click",e=>{let t=e.target.closest(".sum-option");if(!t)return;t.disabled=true;chosen.push(+t.dataset.n);if(chosen.length===2)result(chosen[0]+chosen[1]===target,chosen[0]+chosen[1]===target?"¡Suma perfecta!":"No suman el objetivo.")});return}
if(id==="arrow"){let dirs=[["⬆️","ARRIBA"],["➡️","DERECHA"],["⬇️","ABAJO"],["⬅️","IZQUIERDA"]],d=pick(dirs);a.innerHTML=`<div class="arrow-game"><div style="font-size:8rem">${d[0]}</div><div class="color-word-grid">${dirs.map(x=>`<button class="btn primary" data-d="${x[1]}">${x[1]}</button>`).join("")}</div></div>`;bind(a,"click",e=>{let t=e.target.closest("button[data-d]");if(t)result(t.dataset.d===d[1],t.dataset.d===d[1]?"¡Dirección correcta!":"¡Flecha tramposa!")});return}
if(id==="sequence"){let seq=Array.from({length:6},()=>num(0,8)),i=0,notes=[261.63,293.66,329.63,349.23,392,440,493.88,523.25,587.33];a.innerHTML=`<div class="sequence-game"><p id="tip" class="game-kicker">OBSERVA LOS DESTELLOS</p><div class="sequence-grid">${Array.from({length:9},(_,j)=>`<button class="sequence-tile" data-i="${j}" disabled></button>`).join("")}</div></div>`;let tiles=[...a.querySelectorAll(".sequence-tile")],note=j=>{let A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!state.audio)state.audio=new A;let c=state.audio,o=c.createOscillator(),g=c.createGain(),n=c.currentTime;o.type="sine";o.frequency.value=notes[j];g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.24,n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+.28);o.connect(g).connect(c.destination);o.start(n);o.stop(n+.31)};let flash=k=>{if(k===seq.length){document.querySelector("#tip").textContent="AHORA REPÍTELA";tiles.forEach(t=>t.disabled=false);return}let t=tiles[seq[k]];t.classList.add("lit");note(seq[k]);delay(()=>{t.classList.remove("lit");delay(()=>flash(k+1),120)},420)};delay(()=>flash(0),400);bind(a,"click",e=>{let t=e.target.closest(".sequence-tile");if(!t)return;if(+t.dataset.i!==seq[i])return result(false,"Secuencia incorrecta.");t.classList.add("chosen");delay(()=>t.classList.remove("chosen"),150);if(++i===seq.length)result(true,"¡Secuencia musical perfecta!")});return}
if(id==="ghost"){let miss=num(1,15),vals=shuffle(Array.from({length:15},(_,i)=>i+1).filter(x=>x!==miss));a.innerHTML=`<div class="number-grid">${vals.map(n=>`<button class="number-tile">${n}</button>`).join("")}</div><p class="game-kicker">FALTA UN NÚMERO ENTRE 1 Y 15</p>`;bind(a,"click",e=>{let t=e.target.closest(".number-tile");if(t)result(false,"Ese número sí estaba.")});delay(()=>result(true,`¡Era el ${miss}!`),3000);return}
if(id==="precision"){a.innerHTML=`<div class="catch-field precision-field" id="pf"><p>¡ATRÁPALO!</p><button id="pt" class="precision-target"></button></div>`;let f=document.querySelector("#pf"),t=document.querySelector("#pt"),move=()=>Object.assign(t.style,pos(f,64));move();let iv=setInterval(move,380);state.timers.add(iv);bind(t,"click",e=>{e.stopPropagation();clearInterval(iv);result(true,"¡Toque de precisión!")});bind(f,"click",e=>{if(e.target!==t)result(false,"¡Fallaste el objetivo!")});return}
if(id==="pairs"){let p=pick([["🐶","🐱"],["🍓","🍋"],["🚗","🛵"],["🌙","⭐"],["🐙","🦑"],["🍕","🍔"]]),sp=num(0,24);a.innerHTML=`<p class="game-kicker">ENCUENTRA AL REBELDE</p><div class="pairs-grid" style="grid-template-columns:repeat(5,minmax(0,1fr));gap:5px">${Array.from({length:25},(_,i)=>`<button class="pair-tile" data-ok="${i===sp}" style="font-size:22px;min-height:42px;padding:3px">${i===sp?p[1]:p[0]}</button>`).join("")}</div>`;bind(a,"click",e=>{let t=e.target.closest(".pair-tile");if(t)result(t.dataset.ok==="true",t.dataset.ok==="true"?"¡Encontrado!":"Ese pertenece al grupo.")});return}
if(id==="compare"){let x=num(10,99),y=num(10,99);while(x===y)y=num(10,99);a.innerHTML=`<div class="compare-game"><div class="math-question">${x} &nbsp; ? &nbsp; ${y}</div><div class="color-word-grid"><button id="gt" class="btn primary">MAYOR</button><button id="lt" class="btn primary">MENOR</button></div></div>`;let want=x>y?"gt":"lt";bind(a,"click",e=>{if(e.target.id==="gt"||e.target.id==="lt")result(e.target.id===want,"¡Comparación correcta!")});return}
if(id==="changeColor"){let cols=[["ROJO","#e74c5c"],["AZUL","#3b82d0"],["VERDE","#36b37e"],["AMARILLO","#e4b83d"]],want=pick(cols);a.innerHTML=`<div class="change-game"><p class="game-kicker">ESPERA…</p><div id="change" class="word-target">⚪</div></div>`;delay(()=>{document.querySelector("#change").textContent="¡AHORA!";document.querySelector("#change").style.background=want[1];a.insertAdjacentHTML("beforeend",`<div class="color-word-grid">${shuffle(cols).map(c=>`<button class="color-word" data-c="${c[0]}" style="background:${c[1]}">${c[0]}</button>`).join("")}</div>`);bind(a,"click",e=>{let t=e.target.closest("[data-c]");if(t)result(t.dataset.c===want[0],t.dataset.c===want[0]?"¡Cambio detectado!":"¡Demasiado rápido!")})},1000);return}
if(id==="mirror"){let words=["COHETE","GATO","PIRATA","PLANETA","CASTILLO","DRAGON","QUESO"],w=pick(words),rev=[...w].reverse().join("");form(a,rev,w);return}
}
home();
